/// <reference path="../_internal/sdk.d.ts" />
/// <reference path="../dg.xrmquery.rest.d.ts" />
/// <reference path="../_internal/rest-entities.d.ts" />
/// <reference path="../_internal/EntityEnum/account.d.ts" />
declare namespace RestAPI {
  interface AccountBase extends RestEntity {
    EMailAddress3?: string | null;
    EMailAddress2?: string | null;
    EMailAddress1?: string | null;
    Address1_City?: string | null;
    SLAId?: SDK.EntityReference | null;
    Address1_Longitude?: string | null;
    ModifiedOn?: Date | null;
    Aging90?: SDK.Money | null;
    OverriddenCreatedOn?: Date | null;
    WebSiteURL?: string | null;
    DoNotPostalMail?: boolean | null;
    OpenRevenue?: SDK.Money | null;
    Address1_AddressTypeCode?: SDK.OptionSet<account_address1_addresstypecode> | null;
    SharesOutstanding?: number | null;
    DoNotSendMM?: boolean | null;
    CreditOnHold?: boolean | null;
    Aging30?: SDK.Money | null;
    DoNotBulkPostalMail?: boolean | null;
    Address1_ShippingMethodCode?: SDK.OptionSet<account_address1_shippingmethodcode> | null;
    UTCConversionTimeZoneCode?: number | null;
    SLAInvokedId?: SDK.EntityReference | null;
    OpenDeals_Date?: Date | null;
    OriginatingLeadId?: SDK.EntityReference | null;
    AccountCategoryCode?: SDK.OptionSet<account_accountcategorycode> | null;
    Address2_StateOrProvince?: string | null;
    TerritoryId?: SDK.EntityReference | null;
    Address2_Country?: string | null;
    Address2_Line2?: string | null;
    Aging60_Base?: SDK.Money | null;
    Address1_Line3?: string | null;
    OnHoldTime?: number | null;
    dg_testcalculated_Base?: SDK.Money | null;
    Address1_FreightTermsCode?: SDK.OptionSet<account_address1_freighttermscode> | null;
    CreditLimit?: SDK.Money | null;
    OpenRevenue_Base?: SDK.Money | null;
    Address1_UTCOffset?: number | null;
    PreferredAppointmentTimeCode?: SDK.OptionSet<account_preferredappointmenttimecode> | null;
    NumberOfEmployees?: number | null;
    AccountClassificationCode?: SDK.OptionSet<account_accountclassificationcode> | null;
    Revenue?: SDK.Money | null;
    CustomerTypeCode?: SDK.OptionSet<account_customertypecode> | null;
    ExchangeRate?: string | null;
    Address2_County?: string | null;
    IsPrivate?: boolean | null;
    PrimaryContactId?: SDK.EntityReference | null;
    Telephone3?: string | null;
    ParentAccountId?: SDK.EntityReference | null;
    Address2_City?: string | null;
    StatusCode?: SDK.OptionSet<account_statuscode> | null;
    Address2_Latitude?: string | null;
    CreatedOn?: Date | null;
    DoNotBulkEMail?: boolean | null;
    Address2_Line1?: string | null;
    DoNotFax?: boolean | null;
    MarketCap?: SDK.Money | null;
    Address1_Composite?: string | null;
    OwnershipCode?: SDK.OptionSet<account_ownershipcode> | null;
    OpenDeals_State?: number | null;
    OwningBusinessUnit?: SDK.EntityReference | null;
    Address2_PostalCode?: string | null;
    LastUsedInCampaign?: Date | null;
    ProcessId?: string | null;
    Address2_Line3?: string | null;
    Description?: string | null;
    ModifiedBy?: SDK.EntityReference | null;
    TimeZoneRuleVersionNumber?: number | null;
    Address1_County?: string | null;
    ModifiedOnBehalfBy?: SDK.EntityReference | null;
    Address1_Line1?: string | null;
    DoNotEMail?: boolean | null;
    TerritoryCode?: SDK.OptionSet<account_territorycode> | null;
    Address2_PostOfficeBox?: string | null;
    Address2_Telephone1?: string | null;
    Address2_Telephone2?: string | null;
    Address2_Telephone3?: string | null;
    Aging60?: SDK.Money | null;
    Address1_AddressId?: string | null;
    TraversedPath?: string | null;
    CreditLimit_Base?: SDK.Money | null;
    OwningUser?: SDK.EntityReference | null;
    IndustryCode?: SDK.OptionSet<account_industrycode> | null;
    Address2_Name?: string | null;
    OpenRevenue_State?: number | null;
    PrimarySatoriId?: string | null;
    Name?: string | null;
    EntityImageId?: string | null;
    DoNotPhone?: boolean | null;
    BusinessTypeCode?: SDK.OptionSet<account_businesstypecode> | null;
    PrimaryTwitterId?: string | null;
    CreatedByExternalParty?: SDK.EntityReference | null;
    Address2_Composite?: string | null;
    ShippingMethodCode?: SDK.OptionSet<account_shippingmethodcode> | null;
    Address1_Country?: string | null;
    OwningTeam?: SDK.EntityReference | null;
    Address1_StateOrProvince?: string | null;
    PaymentTermsCode?: SDK.OptionSet<account_paymenttermscode> | null;
    PreferredEquipmentId?: SDK.EntityReference | null;
    CreatedOnBehalfBy?: SDK.EntityReference | null;
    TransactionCurrencyId?: SDK.EntityReference | null;
    AccountRatingCode?: SDK.OptionSet<account_accountratingcode> | null;
    Address1_Telephone1?: string | null;
    Address1_Telephone2?: string | null;
    Address1_Telephone3?: string | null;
    Address1_PostOfficeBox?: string | null;
    Fax?: string | null;
    MasterId?: SDK.EntityReference | null;
    SIC?: string | null;
    OwnerId?: SDK.EntityReference | null;
    Address2_UTCOffset?: number | null;
    StageId?: string | null;
    AccountNumber?: string | null;
    Address2_Fax?: string | null;
    Revenue_Base?: SDK.Money | null;
    Merged?: boolean | null;
    Address2_Longitude?: string | null;
    ModifiedByExternalParty?: SDK.EntityReference | null;
    DefaultPriceLevelId?: SDK.EntityReference | null;
    FtpSiteURL?: string | null;
    Aging90_Base?: SDK.Money | null;
    Address1_PrimaryContactName?: string | null;
    LastOnHoldTime?: Date | null;
    Address1_Line2?: string | null;
    CreatedBy?: SDK.EntityReference | null;
    Address2_AddressTypeCode?: SDK.OptionSet<account_address2_addresstypecode> | null;
    OpenRevenue_Date?: Date | null;
    Address2_UPSZone?: string | null;
    MarketCap_Base?: SDK.Money | null;
    dg_SomeDecimal?: string | null;
    Address1_PostalCode?: string | null;
    TickerSymbol?: string | null;
    CustomerSizeCode?: SDK.OptionSet<account_customersizecode> | null;
    ParticipatesInWorkflow?: boolean | null;
    StockExchange?: string | null;
    PreferredServiceId?: SDK.EntityReference | null;
    PreferredContactMethodCode?: SDK.OptionSet<account_preferredcontactmethodcode> | null;
    ImportSequenceNumber?: number | null;
    Telephone2?: string | null;
    VersionNumber?: number | null;
    PreferredSystemUserId?: SDK.EntityReference | null;
    AccountId?: string | null;
    Telephone1?: string | null;
    Aging30_Base?: SDK.Money | null;
    Address1_Name?: string | null;
    Address1_Fax?: string | null;
    Address1_Latitude?: string | null;
    dg_Test_Med_Underscore?: string | null;
    Address2_ShippingMethodCode?: SDK.OptionSet<account_address2_shippingmethodcode> | null;
    PreferredAppointmentDayCode?: SDK.OptionSet<account_preferredappointmentdaycode> | null;
    dg_TestCalculated?: SDK.Money | null;
    Address2_FreightTermsCode?: SDK.OptionSet<account_address2_freighttermscode> | null;
    Address1_UPSZone?: string | null;
    Address2_AddressId?: string | null;
    Address2_PrimaryContactName?: string | null;
    OpenDeals?: number | null;
    StateCode?: SDK.OptionSet<account_statecode> | null;
  }
  interface Account extends AccountBase {
    Account_Tasks?: Task[] | null;
    Referencedaccount_parent_account?: Account[] | null;
    contact_customer_accounts?: Contact[] | null;
    Referencedaccount_master_account?: Account[] | null;
    dg_account_contact_TestAccount?: Contact[] | null;
    account_primary_contact?: Contact | null;
    Referencingaccount_master_account?: Account | null;
    Referencingaccount_parent_account?: Account | null;
    dg_account_contact?: Contact[] | null;
  }
  interface AccountResult extends AccountBase {
    Account_Tasks?: SDK.Results<TaskResult> | null;
    Referencedaccount_parent_account?: SDK.Results<AccountResult> | null;
    contact_customer_accounts?: SDK.Results<ContactResult> | null;
    Referencedaccount_master_account?: SDK.Results<AccountResult> | null;
    dg_account_contact_TestAccount?: SDK.Results<ContactResult> | null;
    account_primary_contact?: Contact | null;
    Referencingaccount_master_account?: Account | null;
    Referencingaccount_parent_account?: Account | null;
    dg_account_contact?: SDK.Results<ContactResult> | null;
  }
  interface Account_Select extends Account_Expand {
    EMailAddress3: RestAttribute<Account_Select>;
    EMailAddress2: RestAttribute<Account_Select>;
    EMailAddress1: RestAttribute<Account_Select>;
    Address1_City: RestAttribute<Account_Select>;
    SLAId: RestAttribute<Account_Select>;
    Address1_Longitude: RestAttribute<Account_Select>;
    ModifiedOn: RestAttribute<Account_Select>;
    Aging90: RestAttribute<Account_Select>;
    OverriddenCreatedOn: RestAttribute<Account_Select>;
    WebSiteURL: RestAttribute<Account_Select>;
    DoNotPostalMail: RestAttribute<Account_Select>;
    OpenRevenue: RestAttribute<Account_Select>;
    Address1_AddressTypeCode: RestAttribute<Account_Select>;
    SharesOutstanding: RestAttribute<Account_Select>;
    DoNotSendMM: RestAttribute<Account_Select>;
    CreditOnHold: RestAttribute<Account_Select>;
    Aging30: RestAttribute<Account_Select>;
    DoNotBulkPostalMail: RestAttribute<Account_Select>;
    Address1_ShippingMethodCode: RestAttribute<Account_Select>;
    UTCConversionTimeZoneCode: RestAttribute<Account_Select>;
    SLAInvokedId: RestAttribute<Account_Select>;
    OpenDeals_Date: RestAttribute<Account_Select>;
    OriginatingLeadId: RestAttribute<Account_Select>;
    AccountCategoryCode: RestAttribute<Account_Select>;
    Address2_StateOrProvince: RestAttribute<Account_Select>;
    TerritoryId: RestAttribute<Account_Select>;
    Address2_Country: RestAttribute<Account_Select>;
    Address2_Line2: RestAttribute<Account_Select>;
    Aging60_Base: RestAttribute<Account_Select>;
    Address1_Line3: RestAttribute<Account_Select>;
    OnHoldTime: RestAttribute<Account_Select>;
    dg_testcalculated_Base: RestAttribute<Account_Select>;
    Address1_FreightTermsCode: RestAttribute<Account_Select>;
    CreditLimit: RestAttribute<Account_Select>;
    OpenRevenue_Base: RestAttribute<Account_Select>;
    Address1_UTCOffset: RestAttribute<Account_Select>;
    PreferredAppointmentTimeCode: RestAttribute<Account_Select>;
    NumberOfEmployees: RestAttribute<Account_Select>;
    AccountClassificationCode: RestAttribute<Account_Select>;
    Revenue: RestAttribute<Account_Select>;
    CustomerTypeCode: RestAttribute<Account_Select>;
    ExchangeRate: RestAttribute<Account_Select>;
    Address2_County: RestAttribute<Account_Select>;
    IsPrivate: RestAttribute<Account_Select>;
    PrimaryContactId: RestAttribute<Account_Select>;
    Telephone3: RestAttribute<Account_Select>;
    ParentAccountId: RestAttribute<Account_Select>;
    Address2_City: RestAttribute<Account_Select>;
    StatusCode: RestAttribute<Account_Select>;
    Address2_Latitude: RestAttribute<Account_Select>;
    CreatedOn: RestAttribute<Account_Select>;
    DoNotBulkEMail: RestAttribute<Account_Select>;
    Address2_Line1: RestAttribute<Account_Select>;
    DoNotFax: RestAttribute<Account_Select>;
    MarketCap: RestAttribute<Account_Select>;
    Address1_Composite: RestAttribute<Account_Select>;
    OwnershipCode: RestAttribute<Account_Select>;
    OpenDeals_State: RestAttribute<Account_Select>;
    OwningBusinessUnit: RestAttribute<Account_Select>;
    Address2_PostalCode: RestAttribute<Account_Select>;
    LastUsedInCampaign: RestAttribute<Account_Select>;
    ProcessId: RestAttribute<Account_Select>;
    Address2_Line3: RestAttribute<Account_Select>;
    Description: RestAttribute<Account_Select>;
    ModifiedBy: RestAttribute<Account_Select>;
    TimeZoneRuleVersionNumber: RestAttribute<Account_Select>;
    Address1_County: RestAttribute<Account_Select>;
    ModifiedOnBehalfBy: RestAttribute<Account_Select>;
    Address1_Line1: RestAttribute<Account_Select>;
    DoNotEMail: RestAttribute<Account_Select>;
    TerritoryCode: RestAttribute<Account_Select>;
    Address2_PostOfficeBox: RestAttribute<Account_Select>;
    Address2_Telephone1: RestAttribute<Account_Select>;
    Address2_Telephone2: RestAttribute<Account_Select>;
    Address2_Telephone3: RestAttribute<Account_Select>;
    Aging60: RestAttribute<Account_Select>;
    Address1_AddressId: RestAttribute<Account_Select>;
    TraversedPath: RestAttribute<Account_Select>;
    CreditLimit_Base: RestAttribute<Account_Select>;
    OwningUser: RestAttribute<Account_Select>;
    IndustryCode: RestAttribute<Account_Select>;
    Address2_Name: RestAttribute<Account_Select>;
    OpenRevenue_State: RestAttribute<Account_Select>;
    PrimarySatoriId: RestAttribute<Account_Select>;
    Name: RestAttribute<Account_Select>;
    EntityImageId: RestAttribute<Account_Select>;
    DoNotPhone: RestAttribute<Account_Select>;
    BusinessTypeCode: RestAttribute<Account_Select>;
    PrimaryTwitterId: RestAttribute<Account_Select>;
    CreatedByExternalParty: RestAttribute<Account_Select>;
    Address2_Composite: RestAttribute<Account_Select>;
    ShippingMethodCode: RestAttribute<Account_Select>;
    Address1_Country: RestAttribute<Account_Select>;
    OwningTeam: RestAttribute<Account_Select>;
    Address1_StateOrProvince: RestAttribute<Account_Select>;
    PaymentTermsCode: RestAttribute<Account_Select>;
    PreferredEquipmentId: RestAttribute<Account_Select>;
    CreatedOnBehalfBy: RestAttribute<Account_Select>;
    TransactionCurrencyId: RestAttribute<Account_Select>;
    AccountRatingCode: RestAttribute<Account_Select>;
    Address1_Telephone1: RestAttribute<Account_Select>;
    Address1_Telephone2: RestAttribute<Account_Select>;
    Address1_Telephone3: RestAttribute<Account_Select>;
    Address1_PostOfficeBox: RestAttribute<Account_Select>;
    Fax: RestAttribute<Account_Select>;
    MasterId: RestAttribute<Account_Select>;
    SIC: RestAttribute<Account_Select>;
    OwnerId: RestAttribute<Account_Select>;
    Address2_UTCOffset: RestAttribute<Account_Select>;
    StageId: RestAttribute<Account_Select>;
    AccountNumber: RestAttribute<Account_Select>;
    Address2_Fax: RestAttribute<Account_Select>;
    Revenue_Base: RestAttribute<Account_Select>;
    Merged: RestAttribute<Account_Select>;
    Address2_Longitude: RestAttribute<Account_Select>;
    ModifiedByExternalParty: RestAttribute<Account_Select>;
    DefaultPriceLevelId: RestAttribute<Account_Select>;
    FtpSiteURL: RestAttribute<Account_Select>;
    Aging90_Base: RestAttribute<Account_Select>;
    Address1_PrimaryContactName: RestAttribute<Account_Select>;
    LastOnHoldTime: RestAttribute<Account_Select>;
    Address1_Line2: RestAttribute<Account_Select>;
    CreatedBy: RestAttribute<Account_Select>;
    Address2_AddressTypeCode: RestAttribute<Account_Select>;
    OpenRevenue_Date: RestAttribute<Account_Select>;
    Address2_UPSZone: RestAttribute<Account_Select>;
    MarketCap_Base: RestAttribute<Account_Select>;
    dg_SomeDecimal: RestAttribute<Account_Select>;
    Address1_PostalCode: RestAttribute<Account_Select>;
    TickerSymbol: RestAttribute<Account_Select>;
    CustomerSizeCode: RestAttribute<Account_Select>;
    ParticipatesInWorkflow: RestAttribute<Account_Select>;
    StockExchange: RestAttribute<Account_Select>;
    PreferredServiceId: RestAttribute<Account_Select>;
    PreferredContactMethodCode: RestAttribute<Account_Select>;
    ImportSequenceNumber: RestAttribute<Account_Select>;
    Telephone2: RestAttribute<Account_Select>;
    VersionNumber: RestAttribute<Account_Select>;
    PreferredSystemUserId: RestAttribute<Account_Select>;
    AccountId: RestAttribute<Account_Select>;
    Telephone1: RestAttribute<Account_Select>;
    Aging30_Base: RestAttribute<Account_Select>;
    Address1_Name: RestAttribute<Account_Select>;
    Address1_Fax: RestAttribute<Account_Select>;
    Address1_Latitude: RestAttribute<Account_Select>;
    dg_Test_Med_Underscore: RestAttribute<Account_Select>;
    Address2_ShippingMethodCode: RestAttribute<Account_Select>;
    PreferredAppointmentDayCode: RestAttribute<Account_Select>;
    dg_TestCalculated: RestAttribute<Account_Select>;
    Address2_FreightTermsCode: RestAttribute<Account_Select>;
    Address1_UPSZone: RestAttribute<Account_Select>;
    Address2_AddressId: RestAttribute<Account_Select>;
    Address2_PrimaryContactName: RestAttribute<Account_Select>;
    OpenDeals: RestAttribute<Account_Select>;
    StateCode: RestAttribute<Account_Select>;
  }
  interface Account_Filter {
    EMailAddress3: string;
    EMailAddress2: string;
    EMailAddress1: string;
    Address1_City: string;
    SLAId: XQR.EntityReferenceFilter;
    Address1_Longitude: string;
    ModifiedOn: Date;
    Aging90: XQR.ValueContainerFilter<number>;
    OverriddenCreatedOn: Date;
    WebSiteURL: string;
    DoNotPostalMail: boolean;
    OpenRevenue: XQR.ValueContainerFilter<number>;
    Address1_AddressTypeCode: XQR.ValueContainerFilter<account_address1_addresstypecode>;
    SharesOutstanding: number;
    DoNotSendMM: boolean;
    CreditOnHold: boolean;
    Aging30: XQR.ValueContainerFilter<number>;
    DoNotBulkPostalMail: boolean;
    Address1_ShippingMethodCode: XQR.ValueContainerFilter<account_address1_shippingmethodcode>;
    UTCConversionTimeZoneCode: number;
    SLAInvokedId: XQR.EntityReferenceFilter;
    OpenDeals_Date: Date;
    OriginatingLeadId: XQR.EntityReferenceFilter;
    AccountCategoryCode: XQR.ValueContainerFilter<account_accountcategorycode>;
    Address2_StateOrProvince: string;
    TerritoryId: XQR.EntityReferenceFilter;
    Address2_Country: string;
    Address2_Line2: string;
    Aging60_Base: XQR.ValueContainerFilter<number>;
    Address1_Line3: string;
    OnHoldTime: number;
    dg_testcalculated_Base: XQR.ValueContainerFilter<number>;
    Address1_FreightTermsCode: XQR.ValueContainerFilter<account_address1_freighttermscode>;
    CreditLimit: XQR.ValueContainerFilter<number>;
    OpenRevenue_Base: XQR.ValueContainerFilter<number>;
    Address1_UTCOffset: number;
    PreferredAppointmentTimeCode: XQR.ValueContainerFilter<account_preferredappointmenttimecode>;
    NumberOfEmployees: number;
    AccountClassificationCode: XQR.ValueContainerFilter<account_accountclassificationcode>;
    Revenue: XQR.ValueContainerFilter<number>;
    CustomerTypeCode: XQR.ValueContainerFilter<account_customertypecode>;
    ExchangeRate: string;
    Address2_County: string;
    IsPrivate: boolean;
    PrimaryContactId: XQR.EntityReferenceFilter;
    Telephone3: string;
    ParentAccountId: XQR.EntityReferenceFilter;
    Address2_City: string;
    StatusCode: XQR.ValueContainerFilter<account_statuscode>;
    Address2_Latitude: string;
    CreatedOn: Date;
    DoNotBulkEMail: boolean;
    Address2_Line1: string;
    DoNotFax: boolean;
    MarketCap: XQR.ValueContainerFilter<number>;
    Address1_Composite: string;
    OwnershipCode: XQR.ValueContainerFilter<account_ownershipcode>;
    OpenDeals_State: number;
    OwningBusinessUnit: XQR.EntityReferenceFilter;
    Address2_PostalCode: string;
    LastUsedInCampaign: Date;
    ProcessId: XQR.Guid;
    Address2_Line3: string;
    Description: string;
    ModifiedBy: XQR.EntityReferenceFilter;
    TimeZoneRuleVersionNumber: number;
    Address1_County: string;
    ModifiedOnBehalfBy: XQR.EntityReferenceFilter;
    Address1_Line1: string;
    DoNotEMail: boolean;
    TerritoryCode: XQR.ValueContainerFilter<account_territorycode>;
    Address2_PostOfficeBox: string;
    Address2_Telephone1: string;
    Address2_Telephone2: string;
    Address2_Telephone3: string;
    Aging60: XQR.ValueContainerFilter<number>;
    Address1_AddressId: XQR.Guid;
    TraversedPath: string;
    CreditLimit_Base: XQR.ValueContainerFilter<number>;
    OwningUser: XQR.EntityReferenceFilter;
    IndustryCode: XQR.ValueContainerFilter<account_industrycode>;
    Address2_Name: string;
    OpenRevenue_State: number;
    PrimarySatoriId: string;
    Name: string;
    EntityImageId: XQR.Guid;
    DoNotPhone: boolean;
    BusinessTypeCode: XQR.ValueContainerFilter<account_businesstypecode>;
    PrimaryTwitterId: string;
    CreatedByExternalParty: XQR.EntityReferenceFilter;
    Address2_Composite: string;
    ShippingMethodCode: XQR.ValueContainerFilter<account_shippingmethodcode>;
    Address1_Country: string;
    OwningTeam: XQR.EntityReferenceFilter;
    Address1_StateOrProvince: string;
    PaymentTermsCode: XQR.ValueContainerFilter<account_paymenttermscode>;
    PreferredEquipmentId: XQR.EntityReferenceFilter;
    CreatedOnBehalfBy: XQR.EntityReferenceFilter;
    TransactionCurrencyId: XQR.EntityReferenceFilter;
    AccountRatingCode: XQR.ValueContainerFilter<account_accountratingcode>;
    Address1_Telephone1: string;
    Address1_Telephone2: string;
    Address1_Telephone3: string;
    Address1_PostOfficeBox: string;
    Fax: string;
    MasterId: XQR.EntityReferenceFilter;
    SIC: string;
    OwnerId: XQR.EntityReferenceFilter;
    Address2_UTCOffset: number;
    StageId: XQR.Guid;
    AccountNumber: string;
    Address2_Fax: string;
    Revenue_Base: XQR.ValueContainerFilter<number>;
    Merged: boolean;
    Address2_Longitude: string;
    ModifiedByExternalParty: XQR.EntityReferenceFilter;
    DefaultPriceLevelId: XQR.EntityReferenceFilter;
    FtpSiteURL: string;
    Aging90_Base: XQR.ValueContainerFilter<number>;
    Address1_PrimaryContactName: string;
    LastOnHoldTime: Date;
    Address1_Line2: string;
    CreatedBy: XQR.EntityReferenceFilter;
    Address2_AddressTypeCode: XQR.ValueContainerFilter<account_address2_addresstypecode>;
    OpenRevenue_Date: Date;
    Address2_UPSZone: string;
    MarketCap_Base: XQR.ValueContainerFilter<number>;
    dg_SomeDecimal: string;
    Address1_PostalCode: string;
    TickerSymbol: string;
    CustomerSizeCode: XQR.ValueContainerFilter<account_customersizecode>;
    ParticipatesInWorkflow: boolean;
    StockExchange: string;
    PreferredServiceId: XQR.EntityReferenceFilter;
    PreferredContactMethodCode: XQR.ValueContainerFilter<account_preferredcontactmethodcode>;
    ImportSequenceNumber: number;
    Telephone2: string;
    VersionNumber: number;
    PreferredSystemUserId: XQR.EntityReferenceFilter;
    AccountId: XQR.Guid;
    Telephone1: string;
    Aging30_Base: XQR.ValueContainerFilter<number>;
    Address1_Name: string;
    Address1_Fax: string;
    Address1_Latitude: string;
    dg_Test_Med_Underscore: string;
    Address2_ShippingMethodCode: XQR.ValueContainerFilter<account_address2_shippingmethodcode>;
    PreferredAppointmentDayCode: XQR.ValueContainerFilter<account_preferredappointmentdaycode>;
    dg_TestCalculated: XQR.ValueContainerFilter<number>;
    Address2_FreightTermsCode: XQR.ValueContainerFilter<account_address2_freighttermscode>;
    Address1_UPSZone: string;
    Address2_AddressId: XQR.Guid;
    Address2_PrimaryContactName: string;
    OpenDeals: number;
    StateCode: XQR.ValueContainerFilter<account_statecode>;
  }
  interface Account_Expand {
    Account_Tasks: RestExpand<Account_Select,Task_Select>;
    Referencedaccount_parent_account: RestExpand<Account_Select,Account_Select>;
    contact_customer_accounts: RestExpand<Account_Select,Contact_Select>;
    Referencedaccount_master_account: RestExpand<Account_Select,Account_Select>;
    dg_account_contact_TestAccount: RestExpand<Account_Select,Contact_Select>;
    account_primary_contact: RestExpand<Account_Select,Contact_Select>;
    Referencingaccount_master_account: RestExpand<Account_Select,Account_Select>;
    Referencingaccount_parent_account: RestExpand<Account_Select,Account_Select>;
    dg_account_contact: RestExpand<Account_Select,Contact_Select>;
  }
}
interface RestEntities {
  Account: RestMapping<RestAPI.Account,RestAPI.Account_Select,RestAPI.Account_Expand,RestAPI.Account_Filter,RestAPI.AccountResult>;
}
